fix: Retention Bonus doc cancellation. (backport #1189) (#1208)
* Fix (retention_bonus): doctype cancellation.
On cancellation, the user encounters the following error:
    AttributeError - 'RetentionBonus' object has no attribute 'additional_salary'.

* fix(retention_bonus): convert all of 'self.additional_salary' to 'additional_salary'  in cancel function

(cherry picked from commit e64cbdedf2ba1a64c23112e9e30c8f886abff02a)

Co-authored-by: Sajad Alimoradi <115968061+SajadAlimoradi@users.noreply.github.com>