fix: year_list when doesn't exist attendance records
This bug happens when doesn't exist Attendance records.
Fix AttributeError: 'int' object has no attribute 'year'