Undefined value in condition cause error when Sync Condition
1. Creat a new Salary Component, w/o condition or formula defined yet (value is undefined)
2. Use the component in some Salary Structure
3. Attempt to Update Salary Structures with Sync Condition/Formula will show errors.
```
TypeError: SalaryComponent.update_salary_structures() missing 1 required positional argument: 'value'
```