fix: Retention Bonus doc cancellation. (#1189)
* Fix (retention_bonus): doctype cancellation.
On cancellation, the user encounters the following error:
    AttributeError - 'RetentionBonus' object has no attribute 'additional_salary'.

* fix(retention_bonus): convert all of 'self.additional_salary' to 'additional_salary'  in cancel function

(cherry picked from commit e64cbdedf2ba1a64c23112e9e30c8f886abff02a)