Fix 'NoneType' Iteration Error in Salary Slip Loan Processing
This pull request addresses an issue in the `salary_slip_loan_utils.py` where iterating over `NoneType` object caused a `TypeError`. The changes ensure that `doc.loans` is initialized as an empty list if it's `None`, preventing the iteration error.

Changes:
- Initialize `doc.loans` as an empty list if it's `None`.
- Split the logic into initializing `doc.loans` if empty, and then independently iterating over it.

This fix ensures that the salary slip loan processing works smoothly even when `doc.loans` is initially set to `None`.


Full Traceback
````
Traceback with variables (most recent call last):
  File "apps/hrms/hrms/payroll/doctype/payroll_entry/payroll_entry.py", line 1372, in create_salary_slips_for_employees
    frappe.get_doc(args).insert()
      employees = ['E2072', 'E2778', 'E2627', 'E2544', 'E2109', 'E2160', 'E2434', 'E2774', 'E2298', 'E2003', 'E2281', 'E2162', 'E2158', 'E2772', 'E2672', 'E2002', 'E2568', 'E2754', 'E2580', 'E2773', 'E2266', 'E2433', 'E2431', 'E2693', 'E2777']
      args = {'salary_slip_based_on_timesheet': 0, 'payroll_frequency': 'Monthly', 'start_date': '2023-12-01', 'end_date': '2023-12-31', 'company': 'SS Air HVAC Ltd.', 'posting_date': '2024-01-02', 'deduct_tax_for_unclaimed_employee_benefits': 0, 'deduct_tax_for_unsubmitted_tax_exemption_proof': 0, 'payroll_entry': 'HR-PRUN-2024-00003', 'exchange_rate': 1, 'currency': 'BDT', 'doctype': 'Salary Slip', 'employee': 'E2072'}
      publish_progress = False
      payroll_entry = <PayrollEntry: HR-PRUN-2024-00003 docstatus=1>
      salary_slips_exist_for = []
      count = 0
      emp = 'E2072'
      e = TypeError("'NoneType' object is not iterable")
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.run_before_save_methods()
      self = <SalarySlip: Sal Slip/E2072/00023>
      ignore_permissions = None
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 1081, in run_before_save_methods
    self.run_method("validate")
      self = <SalarySlip: Sal Slip/E2072/00023>
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <SalarySlip: Sal Slip/E2072/00023>
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x7f7421e277f0>
      method = 'validate'
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
      self = <SalarySlip: Sal Slip/E2072/00023>
      args = ()
      kwargs = {}
      hooks = [<function apply at 0x7f7421d04ee0>]
      method = 'validate'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      handler = 'erpnext.support.doctype.service_level_agreement.service_level_agreement.apply'
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f7421a33d90>
      compose = <function Document.hook.<locals>.compose at 0x7f7421a33760>
      f = <function Document.run_method.<locals>.fn at 0x7f7421e277f0>
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <SalarySlip: Sal Slip/E2072/00023>
      method = 'validate'
      args = ()
      kwargs = {}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f7421e27f40>
      fn = <function Document.run_method.<locals>.fn at 0x7f7421e277f0>
      hooks = (<function apply at 0x7f7421d04ee0>,)
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
      self = <SalarySlip: Sal Slip/E2072/00023>
      args = ()
      kwargs = {}
      method_object = <bound method SalarySlip.validate of <SalarySlip: Sal Slip/E2072/00023>>
      method = 'validate'
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip.py", line 144, in validate
    self.get_emp_and_working_day_details()
      self = <SalarySlip: Sal Slip/E2072/00023>
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
      args = (<SalarySlip: Sal Slip/E2072/00023>,)
      kwargs = {}
      apply_condition = <function whitelist.<locals>.innerfn.<locals>.<lambda> at 0x7f74217fb640>
      func = <function SalarySlip.get_emp_and_working_day_details at 0x7f74217fb5b0>
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip.py", line 324, in get_emp_and_working_day_details
    self.pull_sal_struct()
      self = <SalarySlip: Sal Slip/E2072/00023>
      struct = 'SS Air HVAC Ltd.'
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip.py", line 400, in pull_sal_struct
    make_salary_slip(self._salary_structure_doc.name, self)
      self = <SalarySlip: Sal Slip/E2072/00023>
      make_salary_slip = <function make_salary_slip at 0x7f7421825240>
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
      args = ('SS Air HVAC Ltd.', <SalarySlip: Sal Slip/E2072/00023>)
      kwargs = {}
      apply_condition = <function whitelist.<locals>.innerfn.<locals>.<lambda> at 0x7f74218251b0>
      func = <function make_salary_slip at 0x7f7421825120>
  File "apps/hrms/hrms/payroll/doctype/salary_structure/salary_structure.py", line 333, in make_salary_slip
    doc = get_mapped_doc(
      source_name = 'SS Air HVAC Ltd.'
      target_doc = <SalarySlip: Sal Slip/E2072/00023>
      as_print = False
      print_format = None
      ignore_permissions = False
      postprocess = <function make_salary_slip.<locals>.postprocess at 0x7f7421825630>
      employee = None
      for_preview = 0
      posting_date = None
  File "apps/frappe/frappe/model/mapper.py", line 148, in get_mapped_doc
    postprocess(source_doc, target_doc)
      from_doctype = 'Salary Structure'
      from_docname = 'SS Air HVAC Ltd.'
      table_maps = {'Salary Structure': {'doctype': 'Salary Slip', 'field_map': {'total_earning': 'gross_pay', 'name': 'salary_structure', 'currency': 'currency'}}}
      target_doc = <SalarySlip: Sal Slip/E2072/00023>
      postprocess = <function make_salary_slip.<locals>.postprocess at 0x7f7421825630>
      ignore_permissions = False
      ignore_child_tables = True
      cached = True
      apply_strict_user_permissions = 0
      source_doc = <SalaryStructure: SS Air HVAC Ltd. docstatus=1>
      row_exists_for_parentfield = {}
  File "apps/hrms/hrms/payroll/doctype/salary_structure/salary_structure.py", line 331, in postprocess
    target.run_method("process_salary_structure", for_preview=for_preview)
      source = <SalaryStructure: SS Air HVAC Ltd. docstatus=1>
      target = <SalarySlip: Sal Slip/E2072/00023>
      employee = None
      for_preview = 0
      posting_date = None
  File "apps/frappe/frappe/model/document.py", line 950, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <SalarySlip: Sal Slip/E2072/00023>
      args = ()
      kwargs = {'for_preview': 0}
      fn = <function Document.run_method.<locals>.fn at 0x7f7421825990>
      method = 'process_salary_structure'
  File "apps/frappe/frappe/model/document.py", line 1316, in composer
    return composed(self, method, *args, **kwargs)
      self = <SalarySlip: Sal Slip/E2072/00023>
      args = ()
      kwargs = {'for_preview': 0}
      hooks = []
      method = 'process_salary_structure'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x7f7421825750>
      compose = <function Document.hook.<locals>.compose at 0x7f7421825bd0>
      f = <function Document.run_method.<locals>.fn at 0x7f7421825990>
  File "apps/frappe/frappe/model/document.py", line 1298, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <SalarySlip: Sal Slip/E2072/00023>
      method = 'process_salary_structure'
      args = ()
      kwargs = {'for_preview': 0}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x7f7421825900>
      fn = <function Document.run_method.<locals>.fn at 0x7f7421825990>
      hooks = ()
  File "apps/frappe/frappe/model/document.py", line 947, in fn
    return method_object(*args, **kwargs)
      self = <SalarySlip: Sal Slip/E2072/00023>
      args = ()
      kwargs = {'for_preview': 0}
      method_object = <bound method SalarySlip.process_salary_structure of <SalarySlip: Sal Slip/E2072/00023>>
      method = 'process_salary_structure'
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip.py", line 1845, in process_salary_structure
    self.calculate_net_pay()
      self = <SalarySlip: Sal Slip/E2072/00023>
      for_preview = 0
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip.py", line 761, in calculate_net_pay
    set_loan_repayment(self)
      self = <SalarySlip: Sal Slip/E2072/00023>
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip_loan_utils.py", line 18, in wrapper
    return function(*args, **kwargs)
      args = (<SalarySlip: Sal Slip/E2072/00023>,)
      kwargs = {}
      function = <function set_loan_repayment at 0x7f74217f9c60>
  File "apps/hrms/hrms/payroll/doctype/salary_slip/salary_slip_loan_utils.py", line 49, in set_loan_repayment
    for payment in doc.get("loans"):
      doc = <SalarySlip: Sal Slip/E2072/00023>
      calculate_amounts = <function calculate_amounts at 0x7f74216bd6c0>
builtins.TypeError: 'NoneType' object is not iterable
````