fix(Payroll): handle empty condition/formula updates from salary components (backport #1766) (#1772)
1. Creat a new Salary Component, w/o condition or formula defined yet (value is undefined)
2. Use the component in some Salary Structure
3. Attempt to Update Salary Structures with Sync Condition/Formula will show errors.
```
TypeError: SalaryComponent.update_salary_structures() missing 1 required positional argument: 'value'
```

(cherry picked from commit adca67eba8c5438e11e06eb819d55ab6048a3131)

Co-authored-by: Kitti U. @ Ecosoft <kittiu@gmail.com>