Add additional checks for number of positions
  Received an error while saving Job Opening which is linked with Staffing Plan, even though all the values are proper in database inside this instance somehow number_of_positions is coming as empty. This Additional check is saving a lot of effort to host and maintain change in separate reositiry. 

______________________________________________________________________
    self.validate_current_vacancies()
  File "apps/hrms/hrms/hr/doctype/job_opening/job_opening.py", line 81, in validate_current_vacancies
    if number_of_positions <= current_count:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'int'